.PHONY: clean All

All:
	@echo "==========Building project:[ favouriteNumber - Debug ]=========="
	@cd "favouriteNumber" && "$(MAKE)" -f  "favouriteNumber.mk"
clean:
	@echo "==========Cleaning project:[ favouriteNumber - Debug ]----------"
	@cd "favouriteNumber" && "$(MAKE)" -f  "favouriteNumber.mk" clean
