.PHONY: clean All

All:
	@echo "==========Building project:[ Votingage - Debug ]=========="
	@cd "Votingage" && "$(MAKE)" -f  "Votingage.mk"
clean:
	@echo "==========Cleaning project:[ Votingage - Debug ]----------"
	@cd "Votingage" && "$(MAKE)" -f  "Votingage.mk" clean
